services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic
      POSTGRES_DB: clinic
    volumes:
      - clinic_pgdata:/var/lib/postgresql/data

volumes:
  clinic_pgdata:
